name: Fetch jours feries
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1"
jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch jours feries
        run: |
          OUTPUT=src/lib.rs cargo c --features=generate
          cargo fmt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Fetch jours feries
          title: Fetch jours feries
          branch: fetch-jours-feries
